version: 3
endpoint: ${HASURA_GRAPHQL_ENDPOINT_HASURA}
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}